// This file is generated by Slice Machine. Update with care!

import Accordion from './Accordion';
import Anchors from './Anchors';
import ArticleBlock from './ArticleBlock';
import Artwork from './Artwork';
import BannerImage from './BannerImage';
import Branding from './Branding';
import CodeBlock from './CodeBlock';
import Convoke from './Convoke';
import DesktopImage from './DesktopImage';
import Embed from './Embed';
import Features from './Features';
import Gallery from './Gallery';
import Headline from './Headline';
import List from './List';
import MobileImage from './MobileImage';
import Panels from './Panels';
import Quote from './Quote';
import Rail from './Rail';
import Scrolly from './Scrolly';
import Shapes from './Shapes';
import Sidenote from './Sidenote';
import Textblock from './Textblock';
import Tiles from './Tiles';
import Timeline from './Timeline';

export {
	Accordion,
	Anchors,
	ArticleBlock,
	Artwork,
	BannerImage,
	Branding,
	CodeBlock,
	Convoke,
	DesktopImage,
	Embed,
	Features,
	Gallery,
	Headline,
	List,
	MobileImage,
	Panels,
	Quote,
	Rail,
	Scrolly,
	Shapes,
	Sidenote,
	Textblock,
	Tiles,
	Timeline,
};

export const components = {
	accordion: Accordion,
	anchors: Anchors,
	article_block: ArticleBlock,
	artwork: Artwork,
	banner_image: BannerImage,
	branding: Branding,
	code_block: CodeBlock,
	convoke: Convoke,
	desktop_image: DesktopImage,
	embed: Embed,
	features: Features,
	gallery: Gallery,
	headline: Headline,
	list: List,
	mobile_image: MobileImage,
	panels: Panels,
	quote: Quote,
	rail: Rail,
	scrolly: Scrolly,
	shapes: Shapes,
	sidenote: Sidenote,
	textblock: Textblock,
	tiles: Tiles,
	timeline: Timeline,
};
